### ISSUE TITLE
Include a helm values.yaml to use with the kube-prometheus-stack 

### ISSUE THREAD

**Issue by dprotaso** [knative-sandbox/monitoring#7]
I got tripped up on this and I wasn't configuring the stack correctly: 

see: https://github.com/knative-sandbox/monitoring/pull/1#issuecomment-874903314

**Comment by dprotaso** [comment]
```
kube-state-metrics:
  metricLabelsAllowlist:
   - pods=[*]
   - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
```
